### ISSUE TITLE
5.24 and earlier don’t have .git/ ?

### ISSUE THREAD

**Issue by FGasper** [Perl/docker-perl-tester#18]
https://github.com/FGasper/p5-TOML-XS/actions/runs/731758471

^ If you look at the failures here, they all fail because there’s no .git/ directory.

5.26:
![image](https://user-images.githubusercontent.com/844867/114125128-d71d5300-98c3-11eb-9931-fce8e8f3e862.png)
https://github.com/FGasper/p5-TOML-XS/runs/2302718045?check_suite_focus=true

5.24:
![image](https://user-images.githubusercontent.com/844867/114125184-ebf9e680-98c3-11eb-9d39-05291b33bf37.png)
https://github.com/FGasper/p5-TOML-XS/runs/2302718053?check_suite_focus=true

Is this an intentional difference between the images?

Thank you!

**Comment by oalders** [comment]
It looks like the `checkout` action doesn't like the version of `git` that it's finding.

https://github.com/FGasper/p5-TOML-XS/runs/2302718053?check_suite_focus=true#step:3:25

Not quite sure what's going on there, since they all use the same base Ubuntu.

**Comment by FGasper** [comment]
Weird. Yeah, even when I put `apt upgrade git` as the first action it says 2.11 is already the latest available git.

**Comment by FGasper** [comment]
Actually the 5.24 ones report being on stretch; 5.26 report buster. @oalders

**Comment by FGasper** [comment]
https://github.com/FGasper/p5-TOML-XS/runs/2313744629?check_suite_focus=true

**Comment by atoomic** [comment]
The checkout action cannot find git >= 2.18 and so use the API to download a tarball
this why you have no .git set... 

You would have to initialize the git repo and set the submodule if needed manually
if you cannot update to 2.18 

https://github.com/FGasper/p5-TOML-XS/runs/2313744629?check_suite_focus=true#step:6:25
```
Deleting the contents of '/__w/p5-TOML-XS/p5-TOML-XS'
The repository will be downloaded using the GitHub REST API
To create a local Git repository instead, add Git 2.18 or higher to the PATH
```

**Comment by atoomic** [comment]
IMO this is not an issue with the image but the way git checkout action works... 
@FGasper I am going to close this case as this is not related to the images themselves but to the version of git available from the distro.

We probably want to rebuild the images with a more modern git binary... I guess that GitHub does not use older version of git due to CVEs
