### ISSUE TITLE
Image for 5.8 to 5.24 use an old version of git

### ISSUE THREAD

**Issue by atoomic** [Perl/docker-perl-tester#19]
This was discovered by @felipe while reporting #18 

We should consider rebuilding the images to ensure we use an up to date version of git.

view https://github.com/FGasper/p5-TOML-XS/runs/2302718149?check_suite_focus=true

**Comment by atoomic** [comment]
this is coming from the Perl images themselves and reported as https://github.com/Perl/docker-perl/issues/100
We can consider either updating git on the images or using our own images...

**Comment by manchicken** [comment]
Is there any way that we can get this updated? It looks like the upstream Perl/docker-perl issue has been resolved, and that they added `-stretch` and `-buster` to the suffix on those containers with the later versions of `git`.

**Comment by oalders** [comment]
This sounds like a great way for someone to celebrate Hacktoberfest. Maybe using the `-buster` images is the way to go?

**Comment by manchicken** [comment]
Way ahead of you :)

**Comment by manchicken** [comment]
Boom: https://github.com/Perl/docker-perl-tester/pull/24 💥

**Comment by manchicken** [comment]
If you'd like to test my built images, you can find those here: https://hub.docker.com/repository/registry-1.docker.io/manchicken/perl-tester-testing/tags?page=1&ordering=last_updated

**Comment by atoomic** [comment]
thanks for taking care of this!

**Comment by oalders** [comment]
Thanks, @manchicken!
