### ISSUE TITLE
install Test2::Harness::Renderer::JUnit by default

### ISSUE THREAD

**Issue by rjbs** [Perl/docker-perl-tester#36]
This is a bit tentative, but:  I think that by having Test2::Harness (yath) and Test2::Harness::Renderer::JUnit
 by default, the [junit-report-action](https://github.com/marketplace/actions/junit-report-action) will become really easy to use and give nice output.

**Comment by rjbs** [comment]
Here's an example of the nice (I think?) report you can get with that:

https://github.com/rjbs/Test-Deep/actions/runs/3865112251/jobs/6588415018

Not needing to install yath or the junit renderer will save maybe 5s per run.

**Comment by oalders** [comment]
A PR would be great. 😀

**Comment by rjbs** [comment]
Ask and ye shall receive.
