### ISSUE TITLE
please provide a devel build

### ISSUE THREAD

**Issue by rjbs** [Perl/docker-perl-tester#45]
See https://github.com/Perl/docker-perl/issues/125

docker-perl has very graciously added a monthly "devel" build of perl's latest dev snapshot, like the current v5.37.8

Being able to test against "latest blead" would be very useful!

I afraid I am unlikely to volunteer for this work, as I barely know how to operate Docker, so instead I hope someone else will be excited by this news and do whatever must be done. :)

**Comment by atoomic** [comment]
I can have a look at it :-)

**Comment by atoomic** [comment]
I think we want to use the `perl:devel` tag 

[5.37.8, 5.37, devel, 5.37.8-bullseye, 5.37-bullseye, devel-bullseye](https://github.com/perl/docker-perl/blob/a0b67543fd56367c403a2f063dfed1a69fdda390/5.037.008-main-bullseye/Dockerfile)

**Comment by rjbs** [comment]
Wow, thanks!  I immediately put this to use getting automated testing for a dist that only works on blead, and now that has led to it being almost ready to work on older perls!

https://github.com/rjbs/Sub-Exporter-Lexical/actions/runs/4026225518

**Comment by atoomic** [comment]
Great I should update the doc with a recommended workflow to use devel where errors should be acceptable and not block a build
